# Site settings
title: "Vitaliy Kinakh's resume"
description: "Vitaliy Kinakh's resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Vitaliy Kinakh"
resume_title:                   "Ph.D. student at University of Geneva"  # add link from SIP group website

# used for the contact button in _layouts/resume.html
resume_contact_email:           "kinakh.vitalii@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     ""
display_header_contact_info:    "false"

resume_header_intro: "<p> Result-driven Ph.D. student with experience in Computer Vision, Deep Learning, Machine Learning, and GeoData Analysis projects of various industries. I am interested in self-supervised learning, explainable and effective AI. I am working on bringing Deep Learning into physics. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/vkinakh"
  #resume_twitter_url:           ""
  # resume_facebook_url:          ""
  resume_linkedin_url:          "https://www.linkedin.com/in/vitaliy-kinakh-606022a4/"
  resume_google_scholar_url:    "https://scholar.google.com/citations?user=tGCmfh0AAAAJ"
  # resume_instagram_url:         ""
  #resume_website_url:           ""
  #resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
